Bump MSRV version in appveyor
rust-bitcoin/rust-bitcoinconsensus pull request #28
Opened 2021-04-22 14:29 UTC by stevenroose

2021-04-22 14:34 UTC, stevenroose commented
I noticed we have both appveyor and Travis here and that doesn't seem necessary.

2021-04-22 22:28 UTC, dr-orlovsky requested changes
Conflicts with #27 - see comment

2021-04-22 22:28 UTC, dr-orlovsky commented on appveyor.yml
> +  - cargo test
This will conflict withchanges introduced by #27

2021-04-26 14:16 UTC, stevenroose commented
Updated

2021-04-26 18:34 UTC, dr-orlovsky approved these changes

2021-05-18 18:10 UTC, TheBlueMatt approved these changes

2021-05-18 18:10 UTC, merged